export const DAY_TYPE = {
  HOLIDAY: "HOLIDAY",
  WORKDAY: "WORKDAY",
};

export const OT_PERIOD = {
  BEFORE: "BEFORE_WORK",
  DURING: "DURING_WORK",
  AFTER: "AFTER_WORK",
};

export const OT_STATUS = {
  DRAFT: 0,
  PENDING_HEAD: 1,
  PENDING_HR: 2,
  APPROVED: 3,
  REJECT_HEAD: 4,
  REJECT_HR: 5,
  CANCEL: 6,
};
